fix(ci/cd): Just skip signing and notarization steps in merge_macos: publish step need merge_os"

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -10,47 +10,47 @@ jobs:
     build:
         uses: ./.github/workflows/build.yml
 
-#    merge_macos:
-#        runs-on: macos-15
-#        needs: build
-#        steps:
-#            - name: Checkout code
-#              uses: actions/checkout@v4
-#
-#            - name: Download all artifacts
-#              uses: actions/download-artifact@v8
-#              with:
-#                  path: dist
-#
-#            - name: Merge macOS universal bundle
-#              run: |
-#                  set -e
-#                  mkdir dist/output
-#
-#                  if [[ ! -f dist/mac-arm64/mac-arm64.zip || ! -f dist/mac-x86_64/mac-x86_64.zip ]]; then
-#                      echo "Missing mac-arm64.zip or mac-x86_64.zip"
-#                      exit 1
-#                  fi
-#                  unzip -q dist/mac-arm64/mac-arm64.zip -d dist/mac-arm64
-#                  unzip -q dist/mac-x86_64/mac-x86_64.zip -d dist/mac-x86_64
-#
-#                  ./Resources/merge_universal.sh \
-#                      dist/mac-arm64/plugins/XDAQ-Neuropixels.bundle \
-#                      dist/mac-x86_64/plugins/XDAQ-Neuropixels.bundle \
-#                      dist/mac-universal/plugins/XDAQ-Neuropixels.bundle
-#
-#            - name: Sign and Notarize macOS universal bundle
-#              env:
-#                  MACOS_CERTIFICATE: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
-#                  MACOS_CERTIFICATE_PWD: ${{ secrets.BUILD_CERTIFICATE_PWD }}
-#                  MACOS_CERTIFICATE_NAME: ${{ secrets.BUILD_CERTIFICATE_NAME }}
-#                  MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
-#                  PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
-#                  PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
-#                  PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
-#              run: |
-#                  set -e
-#
+    merge_macos:
+        runs-on: macos-15
+        needs: build
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
+
+            - name: Download all artifacts
+              uses: actions/download-artifact@v8
+              with:
+                  path: dist
+
+            - name: Merge macOS universal bundle
+              run: |
+                  set -e
+                  mkdir dist/output
+
+                  if [[ ! -f dist/mac-arm64/mac-arm64.zip || ! -f dist/mac-x86_64/mac-x86_64.zip ]]; then
+                      echo "Missing mac-arm64.zip or mac-x86_64.zip"
+                      exit 1
+                  fi
+                  unzip -q dist/mac-arm64/mac-arm64.zip -d dist/mac-arm64
+                  unzip -q dist/mac-x86_64/mac-x86_64.zip -d dist/mac-x86_64
+
+                  ./Resources/merge_universal.sh \
+                      dist/mac-arm64/plugins/XDAQ-Neuropixels.bundle \
+                      dist/mac-x86_64/plugins/XDAQ-Neuropixels.bundle \
+                      dist/mac-universal/plugins/XDAQ-Neuropixels.bundle
+
+            - name: Sign and Notarize macOS universal bundle
+              env:
+                  MACOS_CERTIFICATE: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
+                  MACOS_CERTIFICATE_PWD: ${{ secrets.BUILD_CERTIFICATE_PWD }}
+                  MACOS_CERTIFICATE_NAME: ${{ secrets.BUILD_CERTIFICATE_NAME }}
+                  MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
+                  PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
+                  PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
+                  PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
+              run: |
+                  set -e
+
 #                  echo "Creating keychain"
 #                  security create-keychain -p $MACOS_CI_KEYCHAIN_PWD build.keychain
 #                  security default-keychain -s build.keychain
@@ -91,24 +91,24 @@ jobs:
 #                  echo "Checking signed bundle"
 #                  codesign --verify --verbose=2 \
 #                    dist/mac-universal/plugins/XDAQ-Neuropixels.bundle
-#
-#                  spctl -a -vvv dist/mac-universal/plugins/XDAQ-Neuropixels.bundle
-#
-#                  ditto -c -k --keepParent --rsrc --extattr dist/mac-universal/plugins dist/mac-universal.zip
-#
-#                  echo "Unzipping the final archive to another folder for verification"
-#                  ditto -x -k dist/mac-universal.zip dist/mac-universal-verify
-#
-#                  codesign --verify --verbose=2 \
-#                    dist/mac-universal-verify/plugins/XDAQ-Neuropixels.bundle
-#
-#                  spctl -a -vvv dist/mac-universal-verify/plugins/XDAQ-Neuropixels.bundle
-#
-#            - name: Upload merged macOS bundle
-#              uses: actions/upload-artifact@v7
-#              with:
-#                  name: mac-universal
-#                  path: dist/mac-universal.zip
+
+                  spctl -a -vvv dist/mac-universal/plugins/XDAQ-Neuropixels.bundle
+
+                  ditto -c -k --keepParent --rsrc --extattr dist/mac-universal/plugins dist/mac-universal.zip
+
+                  echo "Unzipping the final archive to another folder for verification"
+                  ditto -x -k dist/mac-universal.zip dist/mac-universal-verify
+
+                  codesign --verify --verbose=2 \
+                    dist/mac-universal-verify/plugins/XDAQ-Neuropixels.bundle
+
+                  spctl -a -vvv dist/mac-universal-verify/plugins/XDAQ-Neuropixels.bundle
+
+            - name: Upload merged macOS bundle
+              uses: actions/upload-artifact@v7
+              with:
+                  name: mac-universal
+                  path: dist/mac-universal.zip
 
     publish:
         runs-on: ubuntu-24.04
